### PR TITLE
Update vim cursor after dw

### PR DESCRIPTION
**Pull request by martinfiers**
After doing a 'dw', it's nice to still see the vim cursor.

Not sure if this is the best way to implement (read: there may be multiple occurrences where you want to update_vim_cursor, probably there will be more to follow but I wanted to be conservative to start with), feedback welcome :)

### CODE REVIEW

**Comment by Nodd** [comment]
I guest it's needed after each call to `editor.cut()` ? Could you check and add it if needed please ?

I'm not sure if the best way is to add the line to each function that need it or make a generic function for selecting some text and deleting it. There would be a similar function for selecting text and copy it, so both of them would call the same subfunction for selection... I'm a bit afraid that it would add too much levels for each function.
I think it's best to keep it case by case for now, and see how it evolves when more commands are added.

**Comment by martinfiers** [comment]
Yes it looks like it's required after every delete command implemented right now (dw, D, dd). Those are the only 3 places where `editor.cut()` is required.

Agreed to do case by case. So what's your suggestion: Just add the `self._widget.update_vim_cursor()` after each deletion command?

**Comment by Nodd** [comment]
Yes, just add this code, thanks.

**Comment by martinfiers** [comment]
Done!

**Comment by Nodd** [comment]
Thanks for your contribution !

**Pull request merged**
